# Generated by Django 5.1.4 on 2024-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=4)),
                ('Rated', models.CharField(max_length=20)),
                ('Released', models.CharField(max_length=100)),
                ('Runtime', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=255)),
                ('Writer', models.CharField(max_length=255)),
                ('Actors', models.CharField(max_length=255)),
                ('Plot', models.TextField()),
                ('Language', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Awards', models.CharField(max_length=255)),
                ('Poster', models.URLField()),
                ('Ratings', models.JSONField()),
                ('Metascore', models.CharField(max_length=50)),
                ('imdbRating', models.CharField(max_length=50)),
                ('imdbVotes', models.CharField(max_length=50)),
                ('imdbID', models.CharField(max_length=50, unique=True)),
                ('Type', models.CharField(max_length=50)),
                ('DVD', models.CharField(max_length=50)),
                ('BoxOffice', models.CharField(max_length=50)),
                ('Production', models.CharField(max_length=100)),
                ('Website', models.URLField()),
                ('Response', models.CharField(max_length=50)),
            ],
        ),
    ]
